// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcOXqZV_xl9vTVBGHGK5m0-mpdkmZtBpM',
    appId: '1:985771086422:web:eff9895b0e75c1257661f7',
    messagingSenderId: '985771086422',
    projectId: 'ecommerce-app-73abf',
    authDomain: 'ecommerce-app-73abf.firebaseapp.com',
    storageBucket: 'ecommerce-app-73abf.appspot.com',
    measurementId: 'G-67CDDJLFPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKKt5goyCTz8EA5IL8Rskz3rFKut0lX-c',
    appId: '1:985771086422:android:ac6188d011b6cb427661f7',
    messagingSenderId: '985771086422',
    projectId: 'ecommerce-app-73abf',
    storageBucket: 'ecommerce-app-73abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7B2aLPO322U-6asLUHZNUMYqPH1ogHg0',
    appId: '1:985771086422:ios:43dd8271db80a9367661f7',
    messagingSenderId: '985771086422',
    projectId: 'ecommerce-app-73abf',
    storageBucket: 'ecommerce-app-73abf.appspot.com',
    androidClientId: '985771086422-f84ol1env945vph211e939itp6l8a5g7.apps.googleusercontent.com',
    iosClientId: '985771086422-oal9jttn750qb00bi66rjqlbsd50g8vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7B2aLPO322U-6asLUHZNUMYqPH1ogHg0',
    appId: '1:985771086422:ios:43dd8271db80a9367661f7',
    messagingSenderId: '985771086422',
    projectId: 'ecommerce-app-73abf',
    storageBucket: 'ecommerce-app-73abf.appspot.com',
    androidClientId: '985771086422-f84ol1env945vph211e939itp6l8a5g7.apps.googleusercontent.com',
    iosClientId: '985771086422-oal9jttn750qb00bi66rjqlbsd50g8vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}